# Generated by Django 3.2.7 on 2021-10-28 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nominas_varias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_nomina', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numero_nomina', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='nomina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=100)),
                ('Dotacion', models.IntegerField(null=True)),
                ('sueldo', models.IntegerField()),
                ('total', models.IntegerField()),
                ('nomina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numero_nomina', to='authApp.nominas_varias')),
            ],
        ),
    ]
